name: master-npm-build                   # 流水线唯一标识，定义一个唯一 ID 标识为 gitee-go-maven，名称为 “Maven-流水线示例” 的流水线
displayName: 'npm编译静态页面'          # 流水线名字
triggers:                              # 流水线触发器配置，支持通过 push 事件触发构建
  push:                                # 通过 push方式触发
    - matchType: PRECISE               # matchType
      branch: master                   # 触发分支名（值为字符串），目前为当前所在分支名，暂不支持跨分支触发
commitMessage: ''                      # 通过匹配当前提交的 CommitMessage 决定是否执行流水线
stages:                                # 构建阶段配置
  - stage:                             # 单个构建阶段
      name: master-npm-build          # 构建阶段唯一标识
      displayName: 'npm编译静态页面'       # 构建阶段名称
      failFast: false                  # 允许快速失败，即当 Stage 中有任务失败时，直接结束整个 Stage
      steps:                           # 构建步骤配置
        - step: npmbuild@1           # 构建步骤的任务类型(枚举类型)，用于决定使用什么构建环境。目前不支持自定义。当前示例为采用 Maven 编译环境
          name: npm-build           # 构建步骤唯一标识，当前示例中定义了一个标识为 maven-build 的构建步骤
          displayName: 'npm编译静态页面'    # 构建步骤名称当前示例中定义了一个名为 “Maven Step” 的构建步骤
          inputs:                      # 构建输入参数设定
            nodeVersion: 12.7
            goals: |                   # 构建脚本，当前示例中使用 Maven 命令初始化、构建一个 Maven 工程并执行输出内容
              npm install
              npm run build
            uploadArtifact: true               # 构建完成后是否将构建物作为制品产出，非必填项，与下方上传参数需同时定义
            uploadArtifactOptions:             # 构建物上传参数，非必填项，与 `uploadArtifact` 参数需同时定义
            artifactPath: './build'         # 构建完成后要打包的构建物所在路径
            artifactRepository: 'npm编译部署'   # 制品库名称，可以理解为一批构建物的集合
            artifactName: 'node-build'     # 构建物打包后的制品名